### ISSUE TITLE
how exactly bpf redirect with BPF_MAP_TYPE_CPUMAP array?

### ISSUE THREAD

**Issue by walidbarakat** [xdp-project/xdp-project#72]
i have a question about how exactly bpf redirect working BPF_MAP_TYPE_CPUMAP array, i saw it's a [new feature](https://github.com/xdp-project/xdp-project/blob/master/areas/cpumap/cpumap04-map-xdp-prog.org) on xdp-project repo and read are adding ability to run another (2nd) XDP-prog on the remote CPU the XDP packets is getting redirected to, i read the [userspace code](https://github.com/torvalds/linux/blob/master/samples/bpf/xdp_redirect_cpu_user.c) and i'm quite confused because i see a redirection interface is required, so in this case this new feature enabling the xdp on interface A to execute another xdp on interface B which recieves the "redirected" packets from interface A, right? if i'm not right so thanks in advance to make the picture clear.

**Comment by tohojo** [comment]
The CPUMAP allows you to redirect XDP frames to be processed on a
different CPU than it was received on, so you can split up the packet
processing between multiple CPUs (like the NIC RSS features, but
programmable with BPF). You can do this without attaching a program to
the cpumap: simply use the bpf_redirect_map() with a cpumap, and you'll
get the redirect, and the normal networking stack will run on the target
CPU.

If you *do* attach a second XDP program to a cpumap, you can also split
up the XDP processing itself between two CPUs. So on the interface, the
XDP program will call bpf_redirect_map(), the packet will get
redirected, and if there's a program installed into the map, that second
program will then be executed *after* the packet has moved to a
different CPU. This second program can then do whatever it wants with
the packet (it's just a normal XDP program), including redirecting it to
another interface, returning XDP_PASS, etc.

The xdp_redirect_cpu sample program you're referring to allows you to
exercise this in various ways, because it comes with a couple of
different example programs to be installed in the cpumap (and thus run
on the remote CPU). *One of* these will redirect the packet, which is
why that userspace program has a `--redirect-device` option. I.e., *if*
you specify that option, the packet will first be redirected to a remote
CPU, and then *on that cpu*, it will be redirected out a different
interface. This can be helpful if you want to split up ingress and
egress processing between CPUs, say.

**Comment by walidbarakat** [comment]
Hi @tohojo,
thanks for explaining, i get something near to that when i read the source code but in some point i doubted about my understanding, but your explanation make it very clear.

thanks.
